export const DateInputField = () => {
    return {
        "key": 42505,
        "type": "date",
        "icon": "date-field",
        "formItemFlag": true,
        "options": {
            "name": "date118043",
            "label": "date",
            "labelAlign": "",
            "type": "date",
            "defaultValue": null,
            "placeholder": "",
            "columnWidth": "200px",
            "size": "",
            "autoFullWidth": true,
            "labelWidth": null,
            "labelHidden": false,
            "readonly": false,
            "disabled": false,
            "hidden": false,
            "clearable": true,
            "editable": false,
            "format": "YYYY-MM-DD",
            "valueFormat": "YYYY-MM-DD HH:mm:ss",
            "required": false,
            "requiredHint": "",
            "validation": "",
            "validationHint": "",
            "customClass": [],
            "labelIconClass": null,
            "labelIconPosition": "rear",
            "labelTooltip": null,
            "onCreated": "",
            "onMounted": "",
            "onChange": "",
            "onFocus": "",
            "onBlur": "",
            "onValidate": ""
        },
        "id": "date118043"
    }
}

export const DateTodayField = () => {
    return {
        "key": 42505,
        "type": "date",
        "icon": "date-field",
        "formItemFlag": true,
        "options": {
            "name": "date118043",
            "label": "date",
            "labelAlign": "",
            "type": "date",
            "defaultValue": null,
            "placeholder": "",
            "columnWidth": "200px",
            "size": "",
            "autoFullWidth": true,
            "labelWidth": null,
            "labelHidden": false,
            "readonly": false,
            "disabled": false,
            "hidden": false,
            "clearable": true,
            "editable": false,
            "format": "YYYY-MM-DD",
            "valueFormat": "YYYY-MM-DD HH:mm:ss",
            "required": false,
            "requiredHint": "",
            "validation": "",
            "validationHint": "",
            "customClass": [],
            "labelIconClass": null,
            "labelIconPosition": "rear",
            "labelTooltip": null,
            "onCreated": "",
            "onMounted": "this.setValue(new Date().toISOString())",
            "onChange": "",
            "onFocus": "",
            "onBlur": "",
            "onValidate": ""
        },
        "id": "date118043"
    }
}